# Build stage
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build -- --configuration production --output-path=dist/achat-frontend

# Runtime stage
FROM node:18-alpine

RUN npm install -g http-server

WORKDIR /app
COPY --from=build /app/dist/achat-frontend .

EXPOSE 8080
CMD ["http-server", "-p", "8080"]
